allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    
    if (project.name != 'app') {
        project.ext.set("flutter", [
            compileSdkVersion: 34,
            minSdkVersion: 21,
            targetSdkVersion: 34,
            versionCode: 1,
            versionName: "1.0"
        ])
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
